

import 'package:get/get_navigation/src/root/internacionalization.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      'Skip':'Skip',
      'personal_information': 'Personal Information',
      'first_name': 'First Name',
      'middle_name': 'Middle Name',
      'last_name': 'Last Name',
      'id_number': 'ID Number',
      'id_issue_date': 'ID Issue Date',
      'id_expiry_date': 'ID Expiry Date',
      'gender': 'Gender (Male / Female)',
      'city': 'City',
      'nationality': 'Nationality',
      'profession': 'Profession',
      'other_profession': 'Other Profession',
      'main_profession': 'Main Profession',
      'continue': 'Continue',
      'Confirm Location': 'Confirm Location',
      "personal_information1": "Personal Information",
      "identity_image": "Identity Image",
      "capture_image": "Capture Image",
      "upload_image": "Upload Image",
      "image_details": "All ID details must be clear in the image",
      "temporary_pin": "Temporary PIN",
      "enter_pin": "Enter the PIN",
      "pin_sent_to": "The code will be sent to your number",
      "resend_code": "Resend Code",
      "submit": "Submit",
      "request_received": "Request Received",
      "request_submitted": "The request has been submitted. We will contact you shortly.",
      "home": "Home",
      "commission_type": "Commission Type",
      "company": "Company",
      "my_commission": "My commission: 20 SAR (Fixed)",
      "total_bookings": "Total Bookings",
      "comprehensive_service": "Comprehensive Service",
      "clients": "Clients",
      "total_earnings": "Total Earnings",
      "monthly_revenue": "Monthly Revenue in Saudi Riyals",
      'change_user': 'Change User',
      'profile': 'Profile',
      'orders': 'Orders',
      'history': 'History',
      'wallet': 'Wallet',
      'review': 'Review',
      "orders1": "Orders",
      "dropdown_label": "Dropdown Label",
      "cleaning_floors": "Cleaning Floors",
      "Decrease":"Decrease",
      "Accept":"Accept",
      "Pending":"Pending",
      "House cleaning":"House cleaning",
      "Electronic appliance repair":"Electronic appliance repair",
      'all': 'All',
      "apartment_cleaning": "Apartment Cleaning",
      "pending": "Pending",
      "completed": "Completed",
      "in_progress": "In Progress",
      "booking_id": "Booking ID",
      "cleaning_apartments": "Cleaning Apartments",
      "date": "Date",
      "time": "Time",
      "about_customer": "About Customer",
      "contact": "Contact",
      "chat": "Chat",
      "payment_details": "Payment Details",
      "identifier": "Identifier",
      "payment_method": "Payment Method",
      "status": "Status",
      "pending": "Pending",
      "total_amount": "Total Amount",
      "price_details": "Price Details",
      "price": "Price",
      "quantity": "Quantity",
      "discount": "Discount (5% off)",
      "coupon": "Coupon (AB45789A)",
      "grand_total": "Grand Total",
      "payable_amount": "Payable Amount",
      "name": "Alhazait Fisher",
      "review2": "I am a mom who bought this product and I am really satisfied with it. Its camera, strong crown, and unique beauty, and also its battery that I charge every two days.",
      "name2": "Charlie Cox",
      "review1": "I was completely satisfied with the delivery time and quality of the product, and I recommend this product to you.",
  "title": "Comments",
      "check_status": "Check Status",
      "pending1": "Pending",
      "start": "Start",
      "end": "End",
      'about_worker': 'About the Worker',
      'message': 'Message',
      'cleaning_expert': 'Cleaning Expert',
      'The reservation has been cancele': 'The reservation has been cancel',
      'You have successfully completed the order.': 'You have successfully completed the order.',
      'Total Amount': 'Total Amount',
      'Retrieve': 'Retrieve',
      'Deposit': 'Deposit',
      'Bonuses': 'Bonuses',
      'Refunded': 'Refunded',
      'Refunded Amounts': 'Refunded Amounts',
      'Records': 'Records',
      'January 30, 2024, 10:23 AM': 'January 30, 2024, 10:23 AM',
      'Order Confirmed': 'Order Confirmed',
      'Return to Home Page': 'Return to Home Page',
      'Your request has been received, and we will assign the provider soon': 'Your request has been received, and we will assign the provider soon',
      'Deposit Amount': 'Deposit Amount',
      'Follow Up': 'Follow Up',
      'Select Deposit Method': 'Select Deposit Method',
      'Select the Amount to Deposit': 'Select the Amount to Deposit',
      'Add Amount Manually': 'Add Amount Manually',
      "withdrawal_successful": "Withdrawal Successful",
      'Select Deposit Method': 'Select Deposit Method',
      'Finished': 'Finished',
      'Screen Capture': 'Screen Capture',
      "payment_successful": "Payment successful. Refresh the screen to see your wallet.",
      "go_to_wallet": "Go to wallet",
      "Paid": "Paid",
      "Completed Orders": "Completed Orders",






    },

    'ar_AR': {
      'Skip':'تخطي',
      'personal_information': 'البيانات الشخصية',
      'first_name': 'الاسم الأول',
      'middle_name': 'اسم الوسط',
      'last_name': 'الاسم الأخير',
      'id_number': 'الهوية رقم',
      'id_issue_date': 'تاريخ اصدار الاقامة',
      'id_expiry_date': 'تاريخ انتهاء الهوية',
      'gender': 'الجنس ( ذكر / أنثى )',
      'city': 'المدينة',
      'nationality': 'الجنسية',
      'profession': 'المهنة',
      'other_profession': 'المهنة الاخرى',
      'main_profession': 'المهنة الاساسي',
      'continue': 'المتابعة',
      'Confirm Location': 'تأكيد الموقع',
      "personal_information1": "المرفقات",
      "identity_image": "صورة الهوية",
      "capture_image": "التقاط صورة",
      "upload_image": "تحميل الصورة",
      "image_details": "يجب أن تكون جميع تفاصيل الهوية واضحة في الصورة",
      "temporary_pin": "رقم سري مؤقت",
      "enter_pin": "ادخل الرقم السري",
      "pin_sent_to": "سيتم ارسال الرمز الى رقمك",
      "resend_code": "اعادة ارسال الرمز",
      "submit": "يقدم",
      "request_received": "تم استلام الطلب",
      "request_submitted": "تم رفع الطلب. سيتم التواصل معكم",
      "home": "بيت",
      "commission_type": "نوع العمولة",
      "company": "شركة",
      "my_commission": "عمولتي : 20 ريال سعودي (ثابتة)",
      "total_bookings": "إجمالي الحجز",
      "comprehensive_service": "الخدمة الشاملة",
      "clients": "عملاء",
      "total_earnings": "مجموع الأرباح",
      "monthly_revenue": "الإيرادات الشهرية ريال سعودي",
      'change_user': 'تغيير المستخدم',
      'profile': 'الحساب التعريفي',
      'orders': 'طلبات',
      'history': 'تاريخ',
      'wallet': 'محفظة',
      'review': 'مراجعة',
      "Decrease":"انخفاض",
          "Accept":"يقبل",
      "orders1": "الطلبات",
      "dropdown_label": "راتبنا للتجربة",
      "cleaning_floors": "تنظيف الأرضيات",
      "Pending": "قيد الانتظار",
      "House cleaning": "تنظيف المنزل",
      "Electronic appliance repair": "إصلاح الأجهزة الإلكترونية",
      'all': 'الجميع',
      "apartment_cleaning": "تنظيف الشقق",
      "pending": "قيد الانتظار",
      "completed": "مكتمل",
      "in_progress": "جاري التنفيذ",
      "booking_id": "معرف الحجز",
      "cleaning_apartments": "تنظيف الشقق",
      "date": "التاريخ",
      "time": "الوقت",
      "about_customer": "حول العميل",
      "contact": "اتصل",
      "chat": "دردشة",
      "payment_details": "بيانات الدفع",
      "identifier": "المعرف",
      "payment_method": "طريقة الدفع",
      "status": "الحالة",
      "pending": "قيد الانتظار",
      "total_amount": "يعرفاف عومجمل",
      "price_details": "تفاصيل السعر",
      "price": "السعر",
      "quantity": "الكمية",
      "discount": "مصحلا (5% off)",
      "coupon": "القسيمة (AB45789A)",
      "grand_total": "الاجمالي الكلي",
      "payable_amount": "يلامحأ عومجمل",
      "name": "الحزایت فشر",
      "review1": "من یک مامی می‌شه که این محصول رو خریدیم و واقعا با تمام وجود راضیم ازش. دوربینش، تاج قوی و زیبایی بی نظیرش و همینطور باطریش که من هر دو روز یک بار شارژش میکنم.",
  "name2": "چارلی کاکس",
  "review2": "من از زمان تحویل و کیفیت کالا کاملا راضی بودم و خرید این کالا رو به شما پیشنهاد میکنم.",
      "title": "التعليقات",
      "check_status": "تحقق من حالة",
      "pending1": "قيد الانتظار",
      "start": "البدء",
      "end": "الانتهاء",
      'about_worker': 'عن العامل',
      'message': 'محادثة',
      'cleaning_expert': 'خبير التنظيف',
      'The reservation has been cancele': 'تم إلغاء الحجز',
      'You have successfully completed the order.': 'لقد أكملت الطلب بنجاح',
      'Total Amount': 'إجمالي المبلغ',
      'Retrieve': 'استرجاع',
      'Deposit': 'إيداع',
      'Bonuses': 'مكافآت',
      'Refunded': 'تم الإسترداد',
      'Refunded Amounts': 'لمبالغ المستردة',
      'Records': 'السجيلات',
      'January 30, 2024, 10:23 AM': '30 يناير 2024، 10:23 ص',
      'Order Confirmed': 'تم تأكيد الطلب',
      'Return to Home Page': 'العودة للصفحة الرئيسية',
      'Your request has been received, and we will assign the provider soon': 'لقد تلقينا طلبك وسنقوم بتعيين المزود قريبًا',
      'Deposit Amount': 'مبلغ الإيداع',
      'Follow Up': 'المتابعة',
      'Select Deposit Method': 'حدد طريقة الإيداع',
      'Select the Amount to Deposit': 'حدد المبلغ الذي تريد إيداعه',
      'Add Amount Manually': 'إضافة المبلغ اليدوي',
      "withdrawal_successful": "تم السحب بنجاح",
      'Finished': 'منتهي',
      'Screen Capture': 'لقطة شاشة',
      "payment_successful": "تم الدفع قم بتحديث الشاشة لتري في محفظتك",
      "go_to_wallet": "اذهب إلى المحفظة",
      "Paid": "تم الدفع",
      "Completed Orders": "الطلبات المكتملة",





    },
  };


}
