import 'package:flutter/material.dart';

@immutable
class CustomAssets {
  const CustomAssets._();
  static const String logo = "assets/images/logo.png";
  static const String saudiflag = "assets/images/saudiflag.png";
  static const String usflag = "assets/images/usflag.jpeg";
  static const String selectServices = "assets/images/slectservices.png";
  static const String commission = "assets/icons/commision.png";
  static const String discount = "assets/icons/Discount.png";
  static const String document = "assets/icons/Document.png";
  static const String profile = "assets/icons/profile.png";
  static const String ticket = "assets/icons/ticket.png";
  static const String home1 = "assets/icons/home1.png";
  static const String languageSelection = "assets/images/languageselection.png";
  static const String plumber = "assets/images/plumber.png";
  static const String cancel = "assets/images/cancel.png";
  static const String check = "assets/icons/check.png";
  static const String successful = "assets/images/successful.png";
  static const String homeicon = "assets/images/tabbar_icons/hom.png";
  static const String graphicon = "assets/images/tabbar_icons/graph.png";
  static const String loveicon = "assets/images/tabbar_icons/Love.png";
  static const String profileicon = "assets/images/tabbar_icons/profile.png";
  static const String qrcodeicon = "assets/images/tabbar_icons/qrcode.png";
  static const String locationicon = "assets/icons/location.png";
  static const String bagicon = "assets/icons/bagicon.png";
  static const String cleaning = "assets/images/cleaning.png";
  static const String hammer = "assets/images/hammer.png";
  static const String handsicon = "assets/images/hands.png";
  static const String tapicon = "assets/images/tapicon.png";
  static const String pluginicon = "assets/images/plugin.png";
  static const String copy = "assets/images/copy.png";
  static const String reverse = "assets/images/reverse.png";
  static const String voucher = "assets/images/voucher.png";
  static const String checkout = "assets/images/checkout.png";
  static const String applepay = "assets/images/applepay.png";
  static const String creditCard = "assets/icons/creditcard.png";
  static const String mada = "assets/icons/mada.png";
  static const String tabby = "assets/icons/tabby.png";
  static const String wallet = "assets/icons/wallet.png";
  static const String tamara = "assets/icons/tamara.png";
  static const String orderSumery = "assets/icons/ordersummery.png";
  static const String success = "assets/images/success.png";
  static const String emptycart = "assets/images/emptycart.png";
  static const String wallethome = "assets/images/wallet.png";
  static const String coins = "assets/icons/coins.png";
  static const String paymentSuccessful = "assets/images/paymentsuccessful.png";
  static const String walletLock = "assets/icons/walletLock.png";
  static const String locations = "assets/images/locations.png";
  static const String fab = "assets/images/fab.png";
  static const String homeicons = "assets/icons/home.png";
  static const String messageicon = "assets/icons/message.png";
  static const String heart = "assets/icons/heart.png";
  static const String banks = "assets/icons/banks.png";
  static const String banksriyadh = "assets/icons/banksriyadh.png";
  static const String WithdrawalSuccessful = "assets/images/withdrawSuccessful.png";
  static const String light = "assets/images/light.png";
  static const String cleaner20 = "assets/images/cleaner20.png";
  static const String banner1 = "assets/images/banner1.jpg";
  static const String banner2 = "assets/images/banner2.jpg";
  static const String banner3 = "assets/images/banner3.jpg";
  static const String male = "assets/images/male.png";
  static const String female = "assets/images/female.png";
  static const String callCalling = "assets/images/call-calling.png";
  static const String cards = "assets/images/cards.png";
  static const String lock = "assets/images/lock.png";
  static const String sheldSecurity = "assets/images/shield-security.png";
  static const String notifications = "assets/images/notifications.png";
  static const String whatsapp = "assets/images/whatsapp.png";
  static const String logout = "assets/images/logout.png";
  static const String lock_Successful_pass = "assets/images/lock_successful_pass.png";
  static const String master = "assets/images/master.png";
  static const String visa = "assets/images/visa.png";
  static const String locationLogo = "assets/images/locationlogo.png";
  static const String chat = "assets/icons/chat.png";


}
